branches:
  only:
    - master
language: ruby
rvm:
  - 2.3.4
  - 2.3.3
  - 2.3.2
  - 2.3.1
  - 2.3.0
  - 2.2.7
  - 2.2.6
  - 2.2.5
  - 2.2.4
  - 2.2.3
  - 2.2.2
  - 2.2.1
  - 2.1.9
  - 2.1.8
  - 2.1.7
  - 2.1.6
  - 2.1.2
  - 1.8.7

before_install:
  - echo "travis before_install"
intall:
  - gem install bundler
script:
  - bundle exec rake build

