build: off
branches:
  only:
    - master
    - devel
environment:
  matrix:
    - RUBY_VERSION: 22
    - RUBY_VERSION: 21
    - RUBY_VERSION: 200
    - RUBY_VERSION: 193

install:
  - "bundle install"
before_test:
  - "ruby -v"
  - "gem -v"
  - "bundle -v"

test_script:
  - "bundle exec rake build"
